name = "boleon"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"

# Pubblica direttamente sul dominio (niente workers.dev)
workers_dev = false
routes = [
  { pattern = "boleon.it", custom_domain = true },
  { pattern = "www.boleon.it", custom_domain = true },
]

[assets]
directory = "./dist"
binding = "ASSETS"
